embeddings {
tensor_name: "embedding/mnist/explicitinterface:1"
tensor_path: "/Users/phuoc.nguyen/repo/score-rca/embeddinglogs/1/embedding/mnist/explicitinterface/tensor.tsv"
metadata_path: "/Users/phuoc.nguyen/repo/score-rca/embeddinglogs/1/embedding/mnist/explicitinterface/metadata.tsv"
sprite {
image_path: "/Users/phuoc.nguyen/repo/score-rca/embeddinglogs/1/embedding/mnist/explicitinterface/sprite.png"
single_image_dim: 28
single_image_dim: 28
}
}
embeddings {
tensor_name: "embedding/mnist/explicitinterface:1"
tensor_path: "/Users/phuoc.nguyen/repo/score-rca/embeddinglogs/1/embedding/mnist/explicitinterface/tensor.tsv"
metadata_path: "/Users/phuoc.nguyen/repo/score-rca/embeddinglogs/1/embedding/mnist/explicitinterface/metadata.tsv"
sprite {
image_path: "/Users/phuoc.nguyen/repo/score-rca/embeddinglogs/1/embedding/mnist/explicitinterface/sprite.png"
single_image_dim: 28
single_image_dim: 28
}
}
